relance_patient/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('rdv/', views.ListRDV.as_view(), name="listing_rdv"),
    path('patient/count/', views.count_patient, name='patient_count'),
]

relance_patient/authentication/urls.py
from django.urls import path
from . import views

#ecriture des urls
app_name = 'authentication'
urlpatterns = [
    path('', views.index, name ='index'),
    path('create/', views.create, name = 'create'),
    path('set_user_inactive/', views.set_user_inactive, name='set_user_inactive'),
    path('set_user_active/', views.set_user_active, name='set_user_active'),
    path('delete/', views.delete, name = 'delete'),
    path("show/<int:pk>", views.show_user, name="show"),
]

relance_patient/dashboard/urls.py
from django.urls import path
from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('site-list/', views.site_list, name='site_list'),
    path('site-list/create/', views.site_create, name='site_create'),
    path('site-list/delete/', views.site_delete, name='site_delete'),
    path('site-list/edit/<int:pk>', views.site_edit, name='site_edit'),
    path('site-list/attribute', views.site_edit, name='site_attribute'),
    path('api/relances/', views.ListRelances.as_view()),
]

relance_patient/mytrack/urls.py
from django.urls import path
from . import views

app_name = 'mytrack'
urlpatterns = [
    path('',views.show_forms, name='forms'),
    path('respect-rdv/', views.respect_rdv, name="respect_rdv"),
    path('patients-venus/', views.list_is_come, name="is_come"),
    path('modif-respect/<str:code_respect>/', views.edit_respect, name="edit_respect"),
    path('rendez-vous/', views.add_rdv, name = "ajout_rdv"),
    path('modif-rdv/<str:code_rdv>/',views.edit_rdv, name="edit_rdv"),
    path('list-rdv/', views.list_rdv, name='list_rdv'),
    path('list-missed-rdv/',views.missed_rdv, name='list_missed_rdv'),
    path('index-testing/',views.add_index, name="ajout_contact"),
    path('modif-index/<str:code_index>/', views.edit_index, name="edit_index"),
    path('list-index/', views.list_index, name='list_index'),
]

relance_patient/patientlisting/urls.py
from django.urls import path
from . import views

app_name = 'patientlisting'

urlpatterns = [
    path('', views.index, name ='pl_index'),
    #extract data from files
    path('all-patients/', views.upload_patient_file, name ="pl_upload_patient_file"),
    path('upload-patient-file/save-content', views.save_file_content, name ="pl_save_file_content"),
    path('download-patient-model-file/', views.download_patient_model_file, name="pl_patient_model_file"),
    path('download-patient-uploaded-file/', views.download_patient_uploaded_file, name="pl_upload_loaded_patient_file"),
    
    #extract data from database
    path('month-rdv-listing/', views.waited_patient, name="month_rdv"),
    path('lost-patient/', views.patient_PVD, name="pl_lost_rdv"),
    path('missed-rdv/', views.missed_rdv_patient, name="pl_missed_rdv"),
    
    #export data into pdf files
    path('export-month-listing/', views.GenerateMonthRDVListingPDF.as_view(), name="pl_export_month_listing"),
    path('export-missed-listing/', views.GenerateMissedRDVListingPDF.as_view(), name="pl_export_missed_listing"),
    path('export-lost-listing/', views.GenerateLostPatientListingPDF.as_view(), name="pl_export_lost_listing"),
]

relance_patient/templates/shared/auth_footer.html
{% load static %}

<section class="section section-footer">
    <ul class='section-footer__menu'>
        <li class='section-footer__item section-footer__item-sejen'>
            <a href="https://www.sejen.ci/" class='section-footer__link' target='_blank'>
                <img src="{% static 'images/app-content/logo_sejen.png' %}" alt="">
            </a>
        </li>

         <li class='section-footer__item section-footer__item-dcli'>
            <a href="https://dcli.co/" class='section-footer__link' target='_blank'>
                <img src="{% static 'images/app-content/logo_dcli.png' %}" alt="">
            </a>
        </li>

         <li class='section-footer__item section-footer__item-dcdj'>
            <a href="https://www.dcdj.ci/" class='section-footer__link' target='_blank'>
                <img src="{% static 'images/app-content/logo_dcdj.png' %}" alt="">
            </a>
        </li>
    </ul>
</section>

relance_patient/templates/shared/auth_text_footer.html
:{% load static %}

<section class="section section-text section-footer">
    <div>
        <p style="font-size:14px;">
            <strong>Des Chiffres et Des Jeunes (DCDJ)</strong> et <strong><a href="https://www.sejen.ci">SEJEN</a></strong> sont des projets du programme&nbsp;<strong>
            <a href="https://dcli.co/">DCLI</a></strong>&nbsp;(Data Collaboratives for Local Impact) piloté par le&nbsp;
            <strong><a href="https://www.mcc.gov/">MCC</a></strong>&nbsp;(Millennium Challenge Corporation) et financé
            par le&nbsp;
            <strong><a href="https://www.pepfar.gov/">PEPFAR</a>&nbsp;</strong>(President’s Emergency Plan For Aids
            Relief).</p>
    </div>
</section>

relance_patient/templates/shared/footer.html
<footer class="app-footer">
    <div class="container">
        <div class="app-footer__content">
            <p>&copy;{{date}} copyright, tous droits réservés</p>
        </div>
    </div>
</footer>

relance_patient/templates/shared/header.html
{% load static %}
<header class="app-header">
    <div class="humberger">
        <span class='app-header__humberger'>
            <i class='flaticon-open-menu'></i>
        </span>
         <p>AS</p>
    </div>
    

    <ul class="app-header__menu">
        <li class="app-header__item">
            <a href="{% url 'authentication_logout' %}" class="app-header__link">
            <i style="font-size:32px;margin-right:5px" class="las la-power-off"></i>
            </a>
        </li>

        {% comment %} <li class="app-header__item">
            <a href="" class="app-header__link">
            <i class="flaticon-envelope"></i>
            </a>
        </li>

        <li class="app-header__item">
            <a href="" class="app-header__link app-header__link-notification">
            <i class="flaticon-bell"></i>
            <span class="app-header__link-notification-value">2</span>
            </a>
        </li> {% endcomment %}
    </ul>

    {% if user.is_authenticated %}
    <div class="app-header__user">
        <div class="app-header__user-info">
            <p>{{ user.user.first_name | capfirst }} {{ user.user.last_name | lower }} </p>
            {% if user.is_super %}
            <small>super admin</small>
            {% elif user.is_admin and not user.is_super %}
            <small>admin</small>
            {% else %}
             <small>staff</small>
            {% endif %}
        </div>
        {% comment %} <a href="">
            
            <img src="{% if user.user.profile %}{% static 'images/app-content/as-pic.jpeg' %}{% else %}{% static 'images/app-content/default-profile.png' %}{% endif %}" class="app-header__user-pic" alt="User priofile picture">
            
        </a> {% endcomment %}
    </div>
    {% endif %}


</header>

relance_patient/templates/shared/sidebar.html
{% load static %}
<div class="app-sidebar">
    <div class="app-sidebar__header">
        <h1 class="app-sidebar__title">
            <img src="{% static 'images/logo-white.svg' %}" alt="Logo blanc Appointent Scheduling couleur" style="width:5rem">
        </h1>
    </div>
   

    <ul class="app-sidebar__menu">
        {% if user.is_admin and not user.is_super %}
        <li class="app-sidebar__item">
            <a href="{% url 'dashboard:home' %}" class="app-sidebar__link {% if path_name.url_name == "home" %}active{% endif %}">
                <i class="flaticon-menu-1"></i>
                Dashboard
            </a>
        </li>
         {% endif %}

        {% if user.is_super %}
         <li class="app-sidebar__item">
            <a href="{% url 'dashboard:site_list' %}" class="app-sidebar__link {% if path_name.url_name == "site_list" or path_name.url_name == "site_create" or path_name.url_name == "site_edit" %}active{% endif %}">
                <i class="flaticon-hospital"></i>
                Sites
            </a>
        </li>
        {% endif %}

         {% if user.is_super %}
        <li class="app-sidebar__item">
            <a href="{% url 'authentication:index' %}" class="app-sidebar__link {% if path_name.url_name == "index" or path_name.url_name == "create" %}active{% endif %}">
                <i class="flaticon-user-1"></i>
                Site admin
            </a>
        </li>
        {% endif %}

        {% if user.is_admin or user.is_staff and not user.is_super %}
        <li class="app-sidebar__item">
            <a href="{% url 'patientlisting:pl_index' %}" class="app-sidebar__link {% if path_name.url_name == "pl_index" or path_name.url_name == "pl_upload_patient_file" or path_name.url_name == "month_rdv" or path_name.url_name == "pl_lost_rdv" or path_name.url_name == "pl_missed_rdv"%}active{% endif %}">
                <i class="flaticon-list"></i>
                Listing patient
            </a>
        </li>
        {% endif %}

        {% if user.is_admin and not user.is_super %}
        <li class="app-sidebar__item">
            <a href="{% url 'activite_relance:list_site_relance' %}" class="app-sidebar__link {% if path_name.url_name == "list_site_relance" %}active{% endif %}">
                <i class="flaticon-diagonal"></i>
                Liste relance
            </a>
        </li>
        {% endif %}

        {% if user.is_admin and not user.is_super %}
        <li class="app-sidebar__item">
            <a href="{% url 'authentication:index' %}" class="app-sidebar__link {% if path_name.url_name == "index" or path_name.url_name == "create" %}active{% endif %}">
                <i class="flaticon-user-1"></i>
                Utilisateurs
            </a>
        </li>
        {% endif %}

        {% if user.is_staff and not user.is_super and not user.is_admin %}
        <li class="app-sidebar__item">
            <a href="{% url 'activite_relance:list_relance' %}" class="app-sidebar__link {% if path_name.url_name == "list_relance" or path_name.url_name == "edit_relance" or path_name.url_name == "add_relance" %}active{% endif %}">
                <i class="flaticon-diagonal"></i>
                Relance patient
            </a>
        </li>
        {% endif %}

        {% if user.is_staff and not user.is_super and not user.is_admin %}
        <li class="app-sidebar__item">
            <a href="{% url 'mytrack:forms' %}" class="app-sidebar__link {% if path_name.url_name == "forms" or path_name.url_name == "list_rdv" or path_name.url_name == "list_index" or path_name.url_name == "is_come" or path_name.url_name == "ajout_rdv" or path_name.url_name == "ajout_contact" or path_name.url_name == "respect_rdv" or path_name.url_name == "edit_rdv" or path_name.url_name == "edit_index" or path_name.url_name == "edit_respect" or path_name.url_name == "list_missed_rdv"  %}active{% endif %}">
                <i class="lab la-wpforms"></i>
                Formulaires
            </a>
        </li>
        {% endif %}

         <li class="app-sidebar__item">
            <a href="{% url 'authentication_profile' %}" class="app-sidebar__link {% if path_name.url_name == "authentication_profile" %}active{% endif %}">
                <i class="flaticon-user"></i>
                Profile
            </a>
        </li>
    </ul>
</div>