relance_patient/activite_relance/urls.py
from django.urls import path
from .views import GeneratePDF
from . import views

app_name = "activite_relance"

urlpatterns = [
    path('list-site-relance/', views.list_site_relance, name='list_site_relance'),
    path('list-relance/', views.list_relance, name='list_relance'),
    path('add-relance/', views.add_relance, name="add_relance"),
    path('edit-relance/<str:relance_code>/', views.edit_relance, name="edit_relance"),
    path('archive-relance/<str:relance_code>/', views.archive_relance, name="archive_relance"),
    path("export-fiche-relance/", GeneratePDF.as_view(), name="export_fiche_relance"),
]

relance_patient/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('rdv/', views.ListRDV.as_view(), name="listing_rdv"),
    path('patient/count/', views.count_patient, name='patient_count'),
]

relance_patient/dashboard/urls.py
from django.urls import path
from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.home, name='home'),
    path('site-list/', views.site_list, name='site_list'),
    path('site-list/create/', views.site_create, name='site_create'),
    path('site-list/delete/', views.site_delete, name='site_delete'),
    path('site-list/edit/<int:pk>', views.site_edit, name='site_edit'),
    path('site-list/attribute', views.site_edit, name='site_attribute'),
    path('api/relances/', views.ListRelances.as_view()),
]

relance_patient/dashboard/models.py
import authentication.models as auth_model
from django.db import models
# from authentication.models import Account


# Model info site
class SiteInfo(models.Model):
    site_code = models.CharField(max_length=100, unique=True)
    site_name = models.CharField(max_length=100)
    service = models.CharField(max_length=30)
    district = models.CharField(max_length=30)
    region = models.CharField(max_length=30)
    direction_region = models.CharField(max_length=30)
    patient_file = models.CharField(max_length=150, blank=True)
    
    def __str__(self):
        return self.site_name

    # Get site admin
    @property
    def site_admin(self):
        accounts = auth_model.Account.objects.filter(is_admin=True, is_super=False)
        for account in accounts:
            if self.site_code == account.user.site_code:
                return account
        return None

relance_patient/dashboard/forms.py
from django import forms
from .models import SiteInfo

class SiteInfoForm(forms.ModelForm):
    class Meta:
        model = SiteInfo
        fields = ['site_code', 'site_name', 'service', 'district', 'region', 'direction_region']
        widgets = {
            'site_code': forms.TextInput(attrs={"id": "site_code","class": "form-control","placeholder": "Code du site",}),

            'site_name': forms.TextInput(attrs={"id": "site_name", 'name':'site_name', "class": "form-control","placeholder": "Nom du site",}),

            'region': forms.TextInput(attrs={"id": "region", "class": "form-control","placeholder": "Region sanitaire",}),

            'district': forms.TextInput(attrs={"id": "district","class": "form-control","placeholder": "District sanitaire",}),

            'service': forms.TextInput(attrs={"id": "service","class": "form-control","placeholder": "Nom du service",}),

            'direction_region': forms.TextInput(attrs={"id": "direction_sanitaire", "class": "form-control","placeholder": "Direction sanitaire",}),
        }

        labels = {
            'site_name': 'Nom du site',
            'site_code': 'Code du site',
            'region': 'Région sanitaire',
            'district': 'Disctrict sanitaire',
            'service': 'Nom du service',
            'direction_region': 'Direction régionanle',
        }

relance_patient/dashboard/views.py
import locale
from datetime import datetime
from django.shortcuts import render, reverse
from django.http import JsonResponse
from django.utils import timezone
from .models import SiteInfo
from authentication.models import Account, User
from .forms import SiteInfoForm
from authentication.models import Account
from activite_relance.models import Patient, FicheRelance
from activite_relance.views import load_relance_list
from relance_patient.utils import get_year_month


from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import permissions


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]

    for row in cursor.fetchall():
        yield dict(zip(columns, row))


def count_users_by_site(site_code):
    users = Account.objects.all()
    return len([user for user in users if user.user.site_code == site_code ])

def count_patients_by_site(site_code):
    patients =  Patient.objects.all()
    return len([patient for patient in patients if patient.site.site_code == site_code])


def get_site_relance(request):
    fiche_relance = FicheRelance.objects.all()
    site_user_relance = []
    relances = []

    for fiche in fiche_relance:
        if fiche.account.user.site_code == request.user.user.site_code:
            site_user_relance.append(fiche)
   
    if site_user_relance:
        for site_fiche in site_user_relance:
            relance_user = site_fiche.account

            for relance in load_relance_list(site_fiche.info_relance):
                relance['owner'] = f"{relance_user.user.first_name} {relance_user.user.last_name}"
                relance['relance_date'] = datetime.strptime(relance['relance_date'], "%Y-%m-%d").date()
                relances.append(relance)

    filtered_relances = list(filter(lambda x:  x['relance_date'], relances))
    return filtered_relances
        

# Dashboard Home
# @login_required(login_url='/auth/login')
def home(request):
    len_account = count_users_by_site(request.user.user.site_code)
    locale.setlocale(locale.LC_ALL, 'fr_FR')
    len_patient = 0
    relances = get_site_relance(request)

    context = {
        'date': timezone.localdate().year,
        'len_account': len_account,
        'len_patient': len_patient,
        'relances': relances[:3],
        'len_relance': len(relances),
        'patient_url': reverse('api:patient_count'),
    }
    return render(request, 'dashboard/home.html', context)


def site_list(request):
    sites = SiteInfo.objects.all()
    accounts = Account.objects.filter(is_admin=True, is_super=False)
    users = []
    for account in accounts:
        users.append(account.user.site_code)

    context = {
        'sites': sites,
        'accounts': accounts
    }
    return render(request, 'dashboard/site_list.html', context)

def site_create(request):
    if request.method == 'POST':
        form_data = request.POST
        form = SiteInfoForm(form_data)
        
        if form.is_valid():
            form.save()

        link = reverse('dashboard:site_list')

        return JsonResponse({
            'status': 200,
            'type': 'success',
            'message': "Le site a été créé", 
            'redirectLink': {
                'link': link,
            }, 
        })

    form = SiteInfoForm(use_required_attribute=False)
    context = {'form': form}
    return render(request, 'dashboard/site_create.html', context)


def site_edit(request, pk):
    site = SiteInfo.objects.get(pk=pk)

    if request.method == 'POST':
        form_data = request.POST
        form = SiteInfoForm(form_data, instance=site)

        if form.is_valid():
            form.save()

            link = reverse('dashboard:site_list')
            return JsonResponse({
                'status': 200,
                'type': 'success',
                'message': "Le site a été modifié", 
                'redirectLink': {
                    'link': link,
                }, 
            })
        else:
            return JsonResponse({
                'status': 404,
                'type': 'error',
                'message': "Erreur de modification", 
                'redirectLink': {
                    'link': link,
                },
            })

    form = SiteInfoForm(instance=site, use_required_attribute=False)
    return render(request, 'dashboard/site_edit.html', {'site': site, 'form': form})

def site_delete(request):
    pass


# API call for get relances data
class ListRelances(APIView):
    """
    View to list all relances in the system.

    * Requires session authentication.
    * Only admin users are able to access this view.
    """
    # authentication_classes = [authentication.SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, format=None):
        """
        Return a list of all relances.
        """
        relances = get_site_relance(request)
        labels = []
        contents = []
        data = {}
        months = get_year_month()
        cc = dict()
        info = {}
        
        for relance in relances:
            
            owner = relance['owner']
            for month in months:
                relance_date_str = relance['relance_date'].strftime("%B")
                if relance_date_str == month[1]:
                    if info.get(month[1]):
                        info[month[1]] += 1
                    else:
                        info.setdefault(month[1], 1)
            if cc.get(owner):
                cc[owner] += 1
            else:
                cc.setdefault(owner, 1)

        for month in months:
            labels.append(month[1])
            if month[1] in info:
                contents.append(info[month[1]])
            else:
                contents.append(0)

        data = {
            'labels': labels,
            'contents': contents,
            'type': 'success',
        }

        return Response(data, status=200)


def handle_404(request):
    return render(request, '404.html')

def handle_403(request):
    return render(request, '403.html')

def handle_500(request):
    return render(request, '500.html')

relance_patient/templates/dashboard/home.html
{% extends 'master.html' %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

    <section class="home-section section-card dash-section">
        <input type="hidden" name="count-patient-url", value="{{ patient_url }}">

        <div class="section__content">
            <div class="section-card__box section-card__box-patient" >
               <div id="count-patient">0</div>
                <span>PATIENTS</span> 
            </div>

            {% comment %} <div class="section-card__box section-card__box-rdv">
                <p>23</p>
                <span>RDV / Semaine</span>
            </div> {% endcomment %}

            <div class="section-card__box section-card__box-pdv">
                <p>{{len_relance}}</p>
                <span>{% if len_relance <= 1 %}Relance{% else %}RELANCES{% endif %}</span>
            </div>

            <div class="section-card__box section-card__box-users">
                <p>{{len_account}}</p>
                <span>{% if len_account <= 1 %}Utilisateur{% else %}Utilisateurs{% endif %}</span>
            </div>
        </div>
    </section>

     <section class="home-section section-card">
        <div class="d-flex flex-aic flex-jcb">
            <p class="section__title">Dernières relances</p>

            <a class="link link-primary" href="{% url 'activite_relance:list_site_relance' %}">Plus de relances <i class="las la-angle-right"></i></a>
        </div>
        



        <div class="card">
            <table class="table" id="admin-relance">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Code</th>
                        <th>Contact</th>
                        <th>Motif</th>
                        <th>Type relance</th>
                        <th>Durée appel</th>
                        <th>Effectuée par</th>
                    </tr>
                </thead>
                <tbody>
                    {% if relances is None %}
                        <tr>
                            <td style="text-align:center">
                                Aucune relance n'est enregistrée
                            </td>
                        </tr>
                    {% else %}
                    {% for relance in relances %}
                    <tr>   

                        <td>{{ relance.relance_date }}</td>

                        <td>{{ relance.patient_code | upper }}</td>

                        <td>{{ relance.patient_contact }}</td>

                        <td>{{ relance.relance_reason | upper }}</td>

                        <td>{{ relance.type_relance.type | upper }}</td>

                        {% if relance.type_relance.relance_call_duration %}
                            <td>{{ relance.type_relance.relance_call_duration }} MIN</td>
                        {% else %}
                            <td>-</td>
                        {% endif %}

                        <td>{{ relance.owner| upper }}</td>

                    </tr>
                    {% endfor %}

                    {% endif %}
                </tbody>
            </table>
        </div>

    </section>

    <section class="home-section section-card">
            {% comment %} 
                <p class="section__title">Graphique des relances effectuées</p> 
                <div class="card">
                    <canvas id="myChart" width="100%" heigh="200px"></canvas> 
                </div>
            {% endcomment %}

            <div class="row">
                <div class="col-md-6 col-lg-6 col-12">
                    <p class="section__title">Graph des relances effectuées</p> 
                    <div class="card">
                        <canvas id="myChart" width="100%" heigh="200px"></canvas>
                    </div>
                </div>

                <div class="col-md-6 col-lg-6 col-12">
                    {% comment %} <p class="section__title">Rapport relances</p> 
                    <div class="card">
                        <canvas id="myChart-2" width="100%" heigh="200px"></canvas>
                    </div> {% endcomment %}
                </div>
            </div>
    </section>

    

{% endblock content %}

relance_patient/templates/dashboard/site_create.html
{% extends 'master.html' %}

{% block title %}Création de site{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

        <div class="user-section-wrapper">
        <div class="card">
            <form action="{% url 'dashboard:site_create' %}" method="post" class="form-create-site">
                {% csrf_token %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        <span class="form-error"></span>
                    </div>
                {% endfor %}

                <button type="submit" class="button button-gradient"><i class="flaticon-floppy-disk"></i> Enregistrer</button>

            </form>
        </div>

        </div>
    </section>

{% endblock content %}

relance_patient/templates/dashboard/site_edit.html
{% extends 'master.html' %}

{% block title %}Modification de site{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

        <div class="user-section-wrapper">
        <div class="card">
            <h1 class="card-title">Modification du site</h1>
            <form action="{% url 'dashboard:site_edit' pk=site.pk %}" method="post" class="form-edit-site">
                {% csrf_token %}
                <input type="hidden" name="site_id" id="site_id" value="{{ site.pk }}">

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        <span class="form-error"></span>
                    </div>
                {% endfor %}

                <button type="submit" class="button button-gradient"><i class="flaticon-floppy-disk"></i> Enregistrer</button>

            </form>
        </div>

        </div>
    </section>

{% endblock content %}

relance_patient/templates/dashboard/site_list.html
{% extends 'master.html' %}

{% block title %}Sites{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

    {% comment %} <div class="row"> {% endcomment %}
        {% comment %} <div class="col-md-8 col-sm-12 m-md-auto m-sm-0"> {% endcomment %}
        <div class='section-block'>
            <a href="{% url 'dashboard:site_create' %}" class="button button-gradient add-user"><i class="flaticon-plus-1"></i> Ajouter un site</a>
        </div>

        <div class="card">
            <table class="table">
                <thead>
                    <tr>
                        <th>Code</th>
                        <th>Nom</th>
                        <th>Region</th>
                        <th>District</th>
                        <th>Direction</th>
                        <th>Service</th>
                        <th>Administrateur</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if sites.count == 0 %}
                        <tr>
                            <td style="text-align:center">
                                Aucun site n'est enregistré
                            </td>
                        </tr>
                    {% else %}
                    {% for site in sites %}
                    <tr>   
                        <td>{{ site.site_code }}</td>

                        <td>{{ site.site_name }}</td>

                        <td>{{ site.region }}</td>

                        <td>{{ site.district }}</td>

                        <td>{{ site.direction_region }}</td>

                        <td>{{ site.service}}</td>

                        {% if site.site_admin != None %}
                            <td>{{ site.site_admin.user.first_name | upper }} {{ site.site_admin.user.last_name | upper }}</td>
                        {% else %}
                            <td>Pas attribué</td>
                        {% endif %}
                       
                        <td class="action">

                            <form action="">
                                {% csrf_token %}
                                <input type="hidden" name="site_id" value="{{ site.pk }}">
                                {% comment %} <a href="{% url 'dashboard:site_attribute' %}" class="button button-small button-ouline-dark"><i class="flaticon-diagonal"></i></a> {% endcomment %}
                                <a href="{% url 'dashboard:site_edit' pk=site.pk %}" class="button button-small button-ouline-success"><i class="flaticon-edit"></i></a>
                                {% comment %} <a href="{% url 'dashboard:site_delete' %}" class="button button-small button-ouline-danger"><i class="flaticon-trash"></i></a> {% endcomment %}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}

                    

                    {% endif %}
                </tbody>
            </table>
        </div>
        {% comment %} </div> {% endcomment %}
        {% comment %} </div> {% endcomment %}
    </section>

{% endblock content %}