relance_patient/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('rdv/', views.ListRDV.as_view(), name="listing_rdv"),
    path('patient/count/', views.count_patient, name='patient_count'),
]

relance_patient/patientlisting/urls.py
from django.urls import path
from . import views

app_name = 'patientlisting'

urlpatterns = [
    path('', views.index, name ='pl_index'),
    #extract data from files
    path('all-patients/', views.upload_patient_file, name ="pl_upload_patient_file"),
    path('upload-patient-file/save-content', views.save_file_content, name ="pl_save_file_content"),
    path('download-patient-model-file/', views.download_patient_model_file, name="pl_patient_model_file"),
    path('download-patient-uploaded-file/', views.download_patient_uploaded_file, name="pl_upload_loaded_patient_file"),
    
    #extract data from database
    path('month-rdv-listing/', views.waited_patient, name="month_rdv"),
    path('lost-patient/', views.patient_PVD, name="pl_lost_rdv"),
    path('missed-rdv/', views.missed_rdv_patient, name="pl_missed_rdv"),
    
    #export data into pdf files
    path('export-month-listing/', views.GenerateMonthRDVListingPDF.as_view(), name="pl_export_month_listing"),
    path('export-missed-listing/', views.GenerateMissedRDVListingPDF.as_view(), name="pl_export_missed_listing"),
    path('export-lost-listing/', views.GenerateLostPatientListingPDF.as_view(), name="pl_export_lost_listing"),
]

relance_patient/patientlisting/models.py
from django.db import models
from authentication.models import Account
class PatientListing(models.Model):
    account = models.ManyToManyField(Account)
    site_code = models.CharField(verbose_name="site_code", max_length=255)
    listing_file = models.URLField(blank=True)
    listing = models.TextField(verbose_name="Listing", blank=True)
    state = models.CharField(max_length=10, default='actif')

    def __str__(self):
        return f"{self.site_code} {self.account.email}"

relance_patient/patientlisting/views.py
import locale, asyncio, calendar, random, math, activite_relance as ar
from time import strftime
from django.http.response import HttpResponse
from numpy.core.getlimits import finfo
import pandas as pd, numpy as np, datetime as dt, tempfile, dateutil
import dashboard.models as dash_mod, json, requests, os
# from pandas.io import json
from operator import attrgetter
from secrets import token_hex
from django.shortcuts import render
from django.http import HttpResponseBadRequest, JsonResponse
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from datetime import datetime, timedelta
from .models import PatientListing
from .extractxlsx import PatientExtractXLSX
from openpyxl.utils import get_column_letter, column_index_from_string
from dashboard.models import SiteInfo
from relance_patient.utils import download as file_download, converter
from pandas import DataFrame
from asgiref.sync import sync_to_async
from activite_relance.models import Patient, DateRDV, Venue, PersonSoutien
from relance_patient.utils import get_month_limit, get_year_month, get_list_year, download_data
from django.views import View
from relance_patient.utils import export_to_pdf
from django.core.paginator import Paginator
from django.db import connections
from relance_patient.settings import base


def generate_filename():
    now_date = datetime.now().date()
    now_time = datetime.now().time()
    return str(now_date).replace('-', '') + str(now_time).split('.')[0].replace(':', '')

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]

    for row in cursor.fetchall():
        yield dict(zip(columns, row))


def check_if_patient_exist(code_patient):
    return ar.models.Patient.objects.filter(code_patient=code_patient).exists()

def save_patient_data(patients:list, rdv_date:list, persones_soutiens: list, site: dash_mod.SiteInfo):
    result = []
    for x, y, z in zip(patients, rdv_date, persones_soutiens):
        patient_data = {"site":site, "first_name":x['Nom_Patient'], "last_name":x['Prenoms_Patient'], "sexe":x['Sexe'], "age":x['Age'], "situation_matrimoniale":x['Situation_matrimoniale'], "contact":x['Contact_Téléphonique'], "domicile":x['Lieu_Habitation']}

        rdv_data = { "date_last_arv":y['Date_dernier_ARV'], "date_proch_arv":y['Date_prochain_ARV'],"date_last_cv":y['Date_Dernier_CV'],"date_proch_cv":y['Date_prochain_CV']}

        person_soutient_data = {"first_name":z['Nom_Personne_Soutien'], "last_name":z['Prénoms_Personne_Soutien'], "adresse":z['Adresse_Personne_Soutien'], "contact":z['Contact_Personne_Soutien'], "lien":z['Lien_Patient']}

        patient, patient_created = ar.models.Patient.objects.update_or_create(code_patient=x['Code_Patient'], defaults = patient_data)
        rdv, rdv_created = ar.models.DateRDV.objects.update_or_create(patient=patient, defaults=rdv_data)
        person, person_created = ar.models.PersonSoutien.objects.update_or_create(patient=patient, defaults=person_soutient_data)
        
        if patient_created and rdv_created and person_created:
            result.append(True)
        else:
            result.append(False)

    return all(result)

# Patient listing home
def index(request):
    now = dt.datetime.now()
    if request.session.get('data_used'):
        try:
            if (now-dt.datetime.strptime(request.session['data_used']['time'],"%Y-%m-%d %H:%M:%S")>dt.timedelta(minutes=5)):
                data_used = {
                    'time':dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    'data':download_data(base.DATA_URL,base.AUTH_SIGDEP)
                }
                request.session['data_used']=data_used
            else:
                pass
        except Exception:
            return render(request, "connexion_error.html")
    else:
        try:
            data_used = {
                'time':dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                'data':download_data(base.DATA_URL,base.AUTH_SIGDEP)
            }
            request.session['data_used']=data_used
        except Exception:
            return render(request, "connexion_error.html")
    return render(request, "patientlisting/index.html")

def extract_patient_data(filename, file_type="xlsx", header=1):
    df = None
    if file_type == "xlsx":
        df = pd.read_excel(filename, header=header)
    
    df_patient = df.loc[:,'Code_Patient':'Contact_Téléphonique']
    df_dateRDV = df.loc[:,'Date_Dernier_CV':'Date_prochain_ARV']
    df_person_soutient = df.loc[:,'Nom_Personne_Soutien':'Lien_Patient']

    patient_list = []
    date_RDV_list = []
    person_soutien_list = []

    for i, row in df_patient.iterrows():
        patient_list.append(row.to_dict())

    for i, row in df_dateRDV.iterrows():
        date_RDV_list.append(row.to_dict())

    for i, row in df_person_soutient.iterrows():
        person_soutien_list.append(row.to_dict())

    return [patient_list, date_RDV_list, person_soutien_list,]


def upload_patient_file(request):
    site = SiteInfo.objects.filter(site_code=request.user.user.site_code).first()
    if request.method == "POST":
        patient_file = request.FILES['patient_file']
        fs = FileSystemStorage()
        file_path = Path(patient_file.name)
        new_file_name = f'{token_hex(8)}{generate_filename()}{file_path.suffix}'
        filename = fs.save(new_file_name, patient_file)
        url = fs.url(filename)
        
        if site:
            site.patient_file = url
            site.save()

            patient_list, dateDRV_list, person_soutien_list = extract_patient_data(url)

            result = sync_to_async(save_patient_data(patient_list, dateDRV_list, person_soutien_list, site), thread_sensitive=True)

            if result:
                return JsonResponse({'type': 'success', 'message': 'Enregistrement des patients réussie'})
            else:
                return JsonResponse({'type': 'error', 'message': 'Erreur d\'enregistrement des patients'})
        else:
            return JsonResponse({'type': 'error', 'message': 'Erreur d\'enregistrement des patients'})

    patients = ar.models.Patient.objects.filter(site=site)
    context = {
        'patients': patients
    }
    return render(request, "patientlisting/upload_patient.html", context)


# Download patient fiche modele file
def download_patient_model_file(request):
    filename = "documents/modele_fiche_patient.xlsx"
    download = file_download(request, filename)
    return download

# Download site last upload file
def download_patient_uploaded_file(request):
    filename = request.user._get_account_site.patient_file
    download = file_download(request, filename, is_uploaded=True)
    return download

#save file content to db
def save_file_content(request):
    if request.method == "POST":
        patient_listing = PatientListing.objects.filter(account=request.user)

def waited_patient(request):
    list_of_month = get_year_month()
    years = get_list_year(2000, 2099)
    now = dt.date.today()
    period = ""
    rdv = []
    session_data = []
    start_date = None
    end_date = None

    if request.GET.get('listing_type')=='interval':
        period = dt.datetime.strptime(request.GET['listing_interval_start'],'%Y-%m-%d').strftime("%d-%m-%Y") + "/" + dt.datetime.strptime(request.GET['listing_interval_end'],'%Y-%m-%d').strftime("%d-%m-%Y")
        start_date = dt.datetime.strptime(request.GET['listing_interval_start'],'%Y-%m-%d').date()
        end_date = dt.datetime.strptime(request.GET['listing_interval_end'],'%Y-%m-%d').date()
    elif request.GET.get('listing_type')=='month':
        month = int(request.GET['listing_month']) or now.month
        year = int(request.GET['listing_year']) or now.year
        period = str([k for k in get_year_month() if k[0]==month][0][1]) + " " + str(year)
        start_date, end_date = get_month_limit(year, month)

    if start_date and end_date:
        data=pd.DataFrame(json.loads(request.session['data_used']['data']))
        for i,row in data.iterrows():
            if start_date<=dt.datetime.strptime(row['proch_rdv'],'%Y-%m-%d').date()<=end_date:
                session_data.append(row.to_dict())
                row['proch_rdv'] = dt.datetime.strptime(row['proch_rdv'].split('/')[0], '%Y-%m-%d').date()
                row['rupture_arv'] = dt.datetime.strptime(row['rupture_arv'].split('/')[0], '%Y-%m-%d').date()
                rdv.append(row.to_dict())  
    if session_data:
        rdv_cal=sorted(session_data, key=lambda x:x['proch_rdv'], reverse=True)
        serialize_data=rdv_cal
        cal_rdv = {
            'type' : 'month',
            'period' : period,
            'data' : json.dumps(serialize_data, default=converter)
        }
        request.session['month_rdv']=cal_rdv
    else:
        pass

    rdv_cal=sorted(rdv, key=lambda x:x['proch_rdv'], reverse=True) 
    paginator = Paginator(rdv_cal, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj, 'years': years, 'cur_year': now.year, 'list_of_month': list_of_month, }

    return render(request, 'patientlisting/listing/month_rdv.html', context)


def missed_rdv_patient(request):
    list_of_month = get_year_month()
    years = get_list_year(2000, 2099)
    now = dt.date.today()
    period = ""
    rdv = []
    session_data = []

    if request.GET.get('listing_month') or request.GET.get('listing_year'):
        month = int(request.GET['listing_month']) or now.month
        year = int(request.GET['listing_year']) or now.year
        period = str([k for k in get_year_month() if k[0]==month][0][1]) + " " + str(year)
        start_date, end_date = get_month_limit(year, month)
        data=pd.DataFrame(json.loads(request.session['data_used']['data']))
        for i,row in data.iterrows():

relance_patient/templates/patientlisting/listing/lost_patient.html
{% extends 'master.html' %}

{% block title %}Listing des perdu de vues{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">



        <div class="d-flex flex-jcb flex-aic">
        <div class='section-block'>

            <form method="GET" action="" class="ml-4 d-flex flex-jcb flex-aic">
                <div class="form-group">
                    <label for="type_losted">Nombre de jours manqués</label>
                    <input type="number" min="0" name="type_losted" id="type_losted" class="form-control" required>
                </div>
               
                <div class="form-group ml-4">
                    <label for="">&nbsp;</label>
                    <button type="submit" class="button button-gradient"><i class="flaticon-shuffle"></i> Générer</button>
                </div>
                
            </form>
     
        </div>
        <div class="div">
            {% comment %} <a href="{% url 'patientlisting:pl_lost_rdv' %}" class="button button-gradient"><i class="las la-undo-alt"></i> Réinitialiser</a> {% endcomment %}
            {% if page_obj %}
            <a href="{% url 'patientlisting:pl_export_lost_listing' %}" class="ml-4 button button-gradient"><i class="flaticon-share"></i> Exporter</a>
             {% endif %}
        </div>

    </div>


        <div class="card">
        <div class="table-fixed">
            <table class="table">
                <thead>
                    <tr>
                        <th>Code patient</th>
                        <th>Sexe</th>
			            <th>Age</th>
                        <th>Régime</th>
                        <th>Date rupture ARV</th>
                        <th>Date RDV clinique</th>
                        {% comment %}
                        <th>Contact</th>
                        {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                    {% if not page_obj %}
                        <tr>
                            <td style="text-align:center">
                                Aucun perdu de vues
                            </td>
                        </tr>
                    {% else %}
                    {% for row in page_obj %}
                    <tr>

                        <td>{{ row.code_patient | upper }}</td>

                        <td>{{ row.sexe | upper }}</td>

			            <td>{{ row.age | upper }} ans</td>

                        <td>{{ row.regime | upper}}</td>

                        <td>{{ row.rupture_arv | date }}</td>

                        <td>{{ row.proch_rdv | date }}</td>
{% comment %}
                        <td>{{ rdv.contact }}</td>

                        <td>{{ rdv.date_rdv }}</td>   
{% endcomment %}                    
                    </tr>
                    {% endfor %}

                    {% endif %}
                </tbody>
            </table>
            </div>
        </div>

         <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a class="button button-gradient" href="?type_losted={{ request.GET.type_losted }}&page=1"><i class="las la-angle-double-left"></i></a>
                    <a class="button button-gradient" href="?type_losted={{ request.GET.type_losted }}&page={{ page_obj.previous_page_number }}"><i class="las la-angle-left"></i></a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="button button-gradient" href="?type_losted={{ request.GET.type_losted }}&page={{ page_obj.next_page_number }}"><i class="las la-angle-right"></i></a>
                    <a class="button button-gradient" href="?type_losted={{ request.GET.type_losted }}&page={{ page_obj.paginator.num_pages }}"><i class="las la-angle-double-right"></i></a>
                {% endif %}
            </span>
        </div>
    </section>

{% endblock content %}

relance_patient/templates/patientlisting/listing/missed_rdv.html
{% extends 'master.html' %}

{% block title %}Rendez-vous manqués{% endblock title %}

{% block content %}

<section class="home-section user-section">
<div class="d-flex flex-jcb flex-aic">
        <div class='section-block'>

            <form method="GET" action="" class="d-flex flex-jcb flex-aic form-missed-rdv">
                
                <div class="form-group">
                    <label for="listing_month">Mois</label>
                    <select name="listing_month" id="listing_month" class="form-control" required>
                        <option value="">Sélectionner le mois</option>
                        {% for month in list_of_month %}
                            <option value="{{month.0 | upper }}">{{ month.1 | upper  }} </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group ml-2">
                    <label for="listing_year">Année</label>
                    <select name="listing_year" id="listing_year" class="form-control" required>
                        <option value="">Sélectionner l'année</option>
                        {% for year in years %}
                            <option {% if year == cur_year %}selected{% endif %} value="{{year}}">{{ year }}</option>
                        {% endfor %}
                    </select>
                </div>
               
                <div class="form-group ml-4">
                    <label for="">&nbsp;</label>
                    <button id="btn-missed-rdv" type="submit" class="button button-gradient"><i class="flaticon-shuffle"></i> Générer</button>
                </div>
                
            </form>
     
        </div>
        <div class="div">    
        {% comment %} <a href="{% url 'patientlisting:pl_missed_rdv' %}" class="button button-gradient"><i class="las la-undo-alt"></i> Rafraichir</a>   {% endcomment %}
        {% if page_obj %}
            <a href="{% url 'patientlisting:pl_export_missed_listing' %}" class="button button-gradient"><i class="flaticon-share"></i> Exporter</a>
        {% endif %}
        </div>
    </div>
        <div class="card">
        <div class="table-fixed">
            <table class="table">
                <thead>
                    <tr>
                        <th>Code patient</th>
                        <th>Sexe</th>
			            <th>Age</th>
                        <th>Régime</th>
                        <th>Date rupture ARV</th>
                        <th>Date RDV clinique</th>
                        {% comment %}
                        <th>Contact</th>
                        {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                {% if not page_obj %}
                        <tr>
                            <td style="text-align:center">
                                Aucun rendez-vous manqué
                            </td>
                        </tr>
                    {% else %}
                    {% for row in page_obj %}
                    <tr>

                        <td>{{ row.code_patient | upper }}</td>

                        <td>{{ row.sexe | upper }}</td>

			            <td>{{ row.age | upper }} ans</td>

                        <td>{{ row.regime | upper}}</td>

                        <td>{{ row.rupture_arv | date }}</td>

                        <td>{{ row.proch_rdv | date }}</td>
{% comment %}
                        <td>{{ rdv.contact }}</td>

                        <td>{{ rdv.date_rdv }}</td>   
{% endcomment %}                    
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a class="button button-gradient" href="?listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page=1"><i class="las la-angle-double-left"></i></a>
                    <a class="button button-gradient" href="?listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page={{ page_obj.previous_page_number }}"><i class="las la-angle-left"></i></a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="button button-gradient" href="?listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page={{ page_obj.next_page_number }}"><i class="las la-angle-right"></i></a>
                    <a class="button button-gradient" href="?listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page={{ page_obj.paginator.num_pages }}"><i class="las la-angle-double-right"></i></a>
                {% endif %}
            </span>
        </div>
        
</section>


{% endblock content %}

relance_patient/templates/patientlisting/listing/month_rdv.html
{% extends 'master.html' %}

{% block title %}Patients attendus{% endblock title %}

{% block content %}

<section class="home-section user-section">
<div class="d-flex flex-jcb flex-aic">
        <div class='section-block'>

            <form method="GET" action="" class="d-flex flex-jcb flex-aic" id="form-patient-listing">

		        <div class="form-group ml-2">
                    <label for="listing_type">Type de listing</label>
                    <select name="listing_type" id="listing_type" class="form-control" required>
                        <option value="">Sélectionner le type</option>
                            <option value="month">Listing du mois</option>
                            <option value="interval">Listing par intervalle</option>
                    </select>
                </div>

                 <div class="form-group ml-2 hide">
                     <label for="listing_interval_start">Date début</label>
                     <input type="date" name="listing_interval_start" id="listing_interval_start" class="form-control" required>
                </div>

                 <div class="form-group ml-2 hide">
                    <label for="listing_interval_end">Date Fin</label>
                    <input type="date" name="listing_interval_end" id="listing_interval_end" class="form-control" required>
                </div>
              	<div class="form-group  ml-2 hide">
                    <label for="listing_month">Mois</label>
                    <select name="listing_month" id="listing_month" class="form-control" required>
                        <option value="">Sélectionner le mois</option>
                        {% for month in list_of_month %}
                            <option value="{{month.0 | upper }}">{{ month.1 | upper  }} </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group ml-2 hide">
                    <label for="listing_year">Année</label>
                    <select name="listing_year" id="listing_year" class="form-control" required>
                        <option value="">Sélectionner l'année</option>
                        {% for year in years %}
                            <option {% if year == cur_year %}selected{% endif %} value="{{year}}">{{ year }}</option>
                        {% endfor %}
                    </select>
                </div>
               
                <div class="form-group ml-4">
                    <label for="">&nbsp;</label>
                    <button type="submit" class="button button-gradient"><i class="flaticon-shuffle"></i> Générer</button>
                </div>
                
            </form>
     
        </div>
        <div class="div">
            {% comment %} <a href="{% url 'patientlisting:month_rdv' %}" class="button button-gradient"><i class="las la-undo-alt" style="font-size:22px;"></i> Réinitialiser</a> {% endcomment %}
            {% if page_obj %}
            <a href="{% url 'patientlisting:pl_export_month_listing' %}" class="ml-4 button button-gradient"><i class="flaticon-share"></i> Exporter</a>
            {% endif %}
        </div>
    </div>
        <div class="card">
        <div class="table-fixed">
            <table class="table">
                <thead>
                    <tr>
                        <th>Code patient</th>
                        <th>Sexe</th>
			            <th>Age</th>
                        <th>Régime</th>
                        <th>Date rupture ARV</th>
                        <th>Date RDV clinique</th>
                        {% comment %}
                        <th>Contact</th>
                        {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                {% if not page_obj %}
                        <tr>
                            <td style="text-align:center">
                                Aucun rendez-vous
                            </td>
                        </tr>
                    {% else %}
                    {% for row in page_obj %}
                    <tr>

                        <td>{{ row.code_patient | upper }}</td>

                        <td>{{ row.sexe | upper }}</td>

			            <td>{{ row.age | upper }} ans</td>

                        <td>{{ row.regime | upper}}</td>

                        <td>{{ row.rupture_arv | date }}</td>

                        <td>{{ row.proch_rdv | date }}</td>
{% comment %}
                        <td>{{ rdv.contact }}</td>

                        <td>{{ rdv.date_rdv }}</td>   
{% endcomment %}                    
                    </tr>
                    {% endfor %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        </div>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a class="button button-gradient" href="?listing_type={{request.GET.listing_type}}&listing_interval_start={{request.GET.listing_interval_start}}&listing_interval_end={{request.GET.listing_interval_end}}&listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page=1"><i class="las la-angle-double-left"></i></a>
                    <a class="button button-gradient" href="?listing_type={{request.GET.listing_type}}&listing_interval_start={{request.GET.listing_interval_start}}&listing_interval_end={{request.GET.listing_interval_end}}&listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page={{ page_obj.previous_page_number }}"><i class="las la-angle-left"></i></a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="button button-gradient" href="?listing_type={{request.GET.listing_type}}&listing_interval_start={{request.GET.listing_interval_start}}&listing_interval_end={{request.GET.listing_interval_end}}&listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page={{ page_obj.next_page_number }}"><i class="las la-angle-right"></i></a>
                    <a class="button button-gradient" href="?listing_type={{request.GET.listing_type}}&listing_interval_start={{request.GET.listing_interval_start}}&listing_interval_end={{request.GET.listing_interval_end}}&listing_month={{ request.GET.listing_month }}&listing_year={{ request.GET.listing_year }}&page={{ page_obj.paginator.num_pages }}"><i class="las la-angle-double-right"></i></a>
                {% endif %}
            </span>
        </div>
        
</section>


{% endblock content %}