relance_patient/activite_relance/urls.py
from django.urls import path
from .views import GeneratePDF
from . import views

app_name = "activite_relance"

urlpatterns = [
    path('list-site-relance/', views.list_site_relance, name='list_site_relance'),
    path('list-relance/', views.list_relance, name='list_relance'),
    path('add-relance/', views.add_relance, name="add_relance"),
    path('edit-relance/<str:relance_code>/', views.edit_relance, name="edit_relance"),
    path('archive-relance/<str:relance_code>/', views.archive_relance, name="archive_relance"),
    path("export-fiche-relance/", GeneratePDF.as_view(), name="export_fiche_relance"),
]

relance_patient/api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path('rdv/', views.ListRDV.as_view(), name="listing_rdv"),
    path('patient/count/', views.count_patient, name='patient_count'),
]

relance_patient/relance_patient/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import login_view, logout_view, profile, profile_set_password, profile_set_info
from dashboard.views import handle_404, handle_500, handle_403

urlpatterns = [
    path('', include('dashboard.urls')),
    path('api/', include('api.urls')),
    path('mytrack/', include('mytrack.urls')),
    path('users/', include('authentication.urls')),
    path('accounts/login/',login_view, name = 'authentication_login'),
    path('accounts/logout/',logout_view, name = 'authentication_logout'),
    path('profile/', profile, name="authentication_profile"),
    path('profile/set_password', profile_set_password, name="authentication_profile_set_password"),
    path('profile/set_info', profile_set_info, name="authentication_profile_set_info"),
    path('patient-listing/', include('patientlisting.urls')),
    path('relance/', include('activite_relance.urls')),
    path('not-found/', handle_404),
    path('not-allow/', handle_403),
    path('error-server/', handle_500),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relance_patient/templates/relance_patient/add.html
{% extends 'master.html' %}

{% block title %}Ajout de relance{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

        <div class="user-section-wrapper">
        <div class="card">
            <form action="{% url 'activite_relance:add_relance' %}" method="post" class="form-add-relance">
                {% csrf_token %}

                <div class="form-group">
                    <label for="relance_date">Date de relance</label>
                    <input type="date" name="relance_date" id="relance_date" class="form-control" placeholder="Date de relance" value="YYYY-MM-DD">
                    <span class="form-error relance_date-error"></span>
                </div>

                 <div class="form-group">
                    <label for="patient_code">Code patient</label>
                    <input type="text" name="patient_code" id="patient_code" class="form-control" placeholder="XXXX/XX/XX/XXXX">
                    <span class="form-error patient_code-error"></span>
                </div>

                 <div class="form-group">
                    <label for="patient_contact">Numéro de télphone patient</label>
                    <input type="text" name="patient_contact" id="patient_contact" class="form-control" placeholder="02020202">
                    <span class="form-error patient_contact-error"></span>
                </div>

                 <div class="form-group">
                    <label for="relance_reason">Motif de la relance</label>
                    <select name="relance_reason" id="relance_reason" class="form-control">
                        <option value="">Sélection le motif</option>
                        {% for motif in motifs %}
                        <option value="{{motif}}">{{ motif | upper }}</option>
                        {% endfor %}
                        <option value="other">AUTRES</option>
                    </select>
                    <span class="form-error relance_reason-error"></span>
                </div>

                <div class="form-group hide" data-relance-reason-other>
                    <label for="relance_reason_other">Précisez le motif</label>
                    <input type="text" name="relance_reason_other" id="relance_reason_other" class="form-control hide" placeholder="Autre motif">
                    <span class="form-error relance_reason_other-error"></span>
                </div>

                <div class="form-group">
                    <label for="relance_type">Type de relance</label>

                    <div class="form-check-inline">

                        <label for="relance_type_visit">
                            <input type="radio" name="relance_type" id="relance_type_visit" value="Visite" class="form-control" checked> Visite à domicile
                        </label>

                        <label for="relance_type_call">
                            <input type="radio" name="relance_type" id="relance_type_call" class="form-control" value="Appel"> Appel
                        </label>

                        <label for="relance_type_call">
                            <input type="radio" name="relance_type" id="relance_type_sms" class="form-control" value="SMS"> SMS
                        </label>
                
                    </div>
                </div>


                <div class="form-group hide" data-call-duration>
                    <label for="call_durantion">Durée appel</label>
                    <input type="text" name="call_durantion" id="call_durantion" class="form-control hide" placeholder="3.5">
                    <span class="form-error call_durantion-error"></span>
                </div>


                <div class="form-group">
                    <label for="relance_feedback">Feedback patient</label>
                    <select name="relance_feedback" id="relance_feedback" class="form-control">
                        <option value="">Sélectionner le feedback</option>
                        {% for feed in feedback %}
                        <option value="{{feed|lower}}">{{feed|upper}}</option>
                        {% endfor %}
                    </select>
                    <span class="form-error relance_feedback-error"></span>
                </div>

                 <div class="form-group hide" data-feedback-visite-date>
                    <label for="feedback_visite_date">Date de visite</label>
                    <input type="date" name="feedback_visite_date" id="feedback_visite_date" class="form-control hide">
                    <span class="form-error feedback_visite_date-error"></span>
                </div>

                <div class="form-group hide" data-feedback-other-center>
                    <label for="feedback_other_center">Nom du centre</label>
                    <input type="text" name="feedback_other_center" id="feedback_other_center" class="form-control hide">
                    <span class="form-error feedback_visite_date-error"></span>
                </div>

                <div class="form-group">
                    <label for="relance_comment">Commentaire</label>
                    <textarea name="relance_comment" id="relance_comment" placeholder="Commentaire" class="form-control"></textarea>
                    <span class="form-error relance_comment-error"></span>
                </div>

                <div class="form-group hide" data-feedback-description>
                    <label for="feedback_description">Feedback description</label>
                    <textarea name="feedback_description" id="feedback_description" placeholder="Message" class="form-control hide"></textarea>
                    <span class="form-error feedback_description-error"></span>
                </div>

                <button type="submit" class="button button-gradient"><i class="flaticon-floppy-disk"></i> Enregistrer</button>

            </form>
        </div>

        </div>
    </section>

{% endblock content %}

relance_patient/templates/relance_patient/all_relance.html
{% extends 'master.html' %}

{% block title %}Site patient relance{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

        <div class='d-flex flex-jcb flex-aic'>
            <div class="section-block__left d-flex flex-jcb flex-aic">
<!--                <input type="hidden" name="filter-relance-table" value="{% url 'activite_relance:list_site_relance' %}">-->
                {% csrf_token %}
<!--                <div class="form-group">-->
<!--                    <label for="search-relance-start-date">Recherche </label>-->
<!--                    <input type="text" id="search-relance-by-text" class="form-control" placeholder="Rechercher">-->
<!--                </div>-->



                <form method="GET" action="" class="d-flex flex-jcb flex-aic">

                    <div class="form-group">
                        <label for="relance_feedback">Feedback</label>
                        <select name="relance_feedback" id="relance_feedback" class="form-control">
                            <option value="">Sélectionner le feedback</option>
                            <option value="auto transfeéré">AUTO TRANSFÉRÉ</option>
                            <option value="transfere">TRANSFÉRÉ</option>
                            <option value="injoingnable">INJOIGNABLE</option>
                            <option value="décédé">DÉCÉDÉ</option>
                            <option value="refus">REFUS</option>
                            <option value="recherche en cours">RECHERCHE EN COURS</option>
                            <option value="arrêt volontaire">ARRÊT VOLONTAIRE</option>
                            <option value="retour aux soins">RETOUR AUX SOINS</option>
                            <option value="promesse de retour">PROMESSE DE RETOUR</option>
                        </select>
                    </div>

                    <div class="form-group ml-2">
                        <label for="search-relance-start-date">Date début</label>
                        <input type="date" name="relance_start_at" id="search-relance-start-date" class="form-control">
                    </div>

                    <div class="form-group ml-2">
                        <label for="search-relance-start-date">Date fin</label>
                        <input type="date" name="relance_end_at" id="search-relance-end-date" class="form-control">
                    </div>

                    <div class="form-group ml-2">
                    <label for="">&nbsp;</label>
                        <button type="submit" class="button button-gradient"><i class="flaticon-zoom"></i> Recherche</button>
                    </div>

                </form>



            </div>
            
            <div class="section-block__right">
                <a href="{% url 'activite_relance:list_site_relance' %}" class="button button-gradient"><i class="flaticon-refresh"></i> Actualisé</a>
                {% comment %} <a href="{% url 'activite_relance:export_fiche_relance' %}" class="button button-small button-gradient"><i class="flaticon-share"></i> Exporter</a> {% endcomment %}
            </div>
        </div>

        <div class="card mb-4">
            <table class="table" id="admin-relance">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Code patient</th>
                        <th>Contact patient</th>
                        <th>Motif</th>
                        <th>Type de relance</th>
                        <th>Durée appel</th>
                        <th>Feedback</th>
                        <th>Effectuée par</th>
                    </tr>
                </thead>
                <tbody>
                    {% if relances|length == 0 %}
                        <tr>
                            <td style="text-align:center">
                                Aucune relance n'est enregistrée
                            </td>
                        </tr>
                    {% else %}
                    {% for relance in relances %}
                    <tr>   

                        <td>{{ relance.relance_date | date }}</td>

                        <td>{{ relance.patient_code | upper }}</td>

                        <td>{{ relance.patient_contact }}</td>

                        <td>{{ relance.relance_reason | upper }}</td>

                        <td>{{ relance.type_relance.type | capfirst }}</td>

                        {% if relance.type_relance.relance_call_duration %}
                            <td>{{ relance.type_relance.relance_call_duration }} min</td>
                        {% else %}
                            <td>-</td>
                        {% endif %}

                       

                        <td>{{ relance.feedback.type | capfirst }}</td>

                        <td>{{ relance.owner| capfirst }}</td>

                

                        {% comment %} <td class="action">

                            <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="relance_code" value="{{ relance.relance_code }}">
                                <a data-archive-relance href="{% url 'activite_relance:archive_relance' relance_code=relance.relance_code %}" class="button button-small button-ouline-dark"><i class="flaticon-file-1"></i></a>
                                <a data-edit-relance href="{% url 'activite_relance:edit_relance' relance_code=relance.relance_code %}" class="button button-small button-ouline-success"><i class="flaticon-edit"></i></a>
                            </form>
                        </td> {% endcomment %}

                    </tr>
                    {% endfor %}

                    {% endif %}
                </tbody>
            </table>
        </div>

        {% comment %} <div class="block-filter">
             <div class="form-group">
                <label for="relance_type">Filtres</label>

                <div class="form-check-inline">

                    <label for="all-relance">
                        <input type="radio" name="relance-archive" id="all-relance" value="all" class="form-control" checked> Toutes
                    </label>

                    <label for="non-archive-relance">
                        <input type="radio" name="relance-archive" id="non-archive-relance" class="form-control" value="non-archive"> Relances non archivées
                    </label>

                    <label for="archive-relance">
                        <input type="radio" name="relance-archive" id="archive-relance" class="form-control" value="archive"> Relances archivées
                    </label>
            
                </div>
            </div> {% endcomment %}
            
        </div>
    </section>

{% endblock content %}

relance_patient/templates/relance_patient/edit.html
{% extends 'master.html' %}

{% block title %}Modification de relance{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

        <div class="user-section-wrapper">
        <div class="card">
            <form action="{% url 'activite_relance:edit_relance' relance_code=relance.relance_code %}" method="post" class="form-edit-relance">
                {% csrf_token %}

                <input type="hidden" name="relance_code" value="{{ relance.relance_code }}">

                <div class="form-group">
                    <label for="relance_date">Date de relance</label>
                    <input type="date" name="relance_date" id="relance_date" class="form-control" placeholder="Date de relance" value="{{ relance.relance_date }}">
                    <span class="form-error relance_date-error"></span>
                </div>

                 <div class="form-group">
                    <label for="patient_code">Code patient</label>
                    <input type="text" name="patient_code" id="patient_code" class="form-control" placeholder="XXXX/XX/XX/XXXX" value="{{ relance.patient_code  }}">
                    <span class="form-error patient_code-error"></span>
                </div>

                 <div class="form-group">
                    <label for="patient_contact">Numéro de télphone patient</label>
                    <input type="text" name="patient_contact" id="patient_contact" class="form-control" placeholder="02020202" value="{{ relance.patient_contact }}">
                    <span class="form-error patient_contact-error"></span>
                </div>

                 <div class="form-group">
                    <label for="relance_reason">Motif de la relance</label>
                    <select name="relance_reason" id="relance_reason" class="form-control">
                        <option value="">Sélection le motif</option>
                        {% for motif in motifs %}
                            <option value="{{motif}}" {% if relance.relance_reason == motif %}selected{% else %}{% endif %}>{{motif | upper}}</option>
                        {% endfor %}
                        {% comment %} <option value="arv" {% if relance.relance_reason == "arv" %}selected{% else %}{% endif %}>ARV</option>
                        <option value="charge virale" {% if relance.relance_reason == "charge virale" %}selected{% else %}{% endif %}>CHARGE VIRALE</option> {% endcomment %}
                        <option value="other" {% if not relance.relance_reason in motifs and not relance.relance_reason == "" %}selected{% else %}{% endif %}>AUTRES</option>
                    </select>
                    <span class="form-error relance_reason-error"></span>
                </div>

                 <div class="form-group hide" data-relance-reason-other>
                    <label for="relance_reason_other">Précisez le motif</label>
                    <input type="text" name="relance_reason_other" value="{% if not relance.relance_reason in motifs and not relance.relance_reason == '' %}{{relance.relance_reason}}{% else %}{% endif %}" id="relance_reason_other" class="form-control hide" placeholder="Autre motif">
                    <span class="form-error relance_reason_other-error"></span>
                </div>

                <div class="form-group">
                    <label for="relance_type">Type de relance</label>

                    <div class="form-check-inline">

                        <label for="relance_type_visit">
                            <input type="radio" name="relance_type" id="relance_type_visit" value="visite" class="form-control" {% if relance.type_relance.type.lower == "visite" %}checked{% endif %}> Visite à domicile
                        </label>

                        <label for="relance_type_call">
                            <input type="radio" name="relance_type" id="relance_type_call" class="form-control" value="appel" {% if relance.type_relance.type.lower == "appel" %}checked{% endif %}> Appel
                        </label>

                        <label for="relance_type_sms">
                            <input type="radio" name="relance_type" id="relance_type_sms" class="form-control" value="SMS"  {% if relance.type_relance.type.lower == "sms" %}checked{% endif %}> SMS
                        </label>
                
                    </div>
                </div>


                <div class="form-group hide" data-call-duration>
                    <label for="call_durantion">Durée appel</label>
                    <input type="text" name="call_durantion" id="call_durantion" class="form-control hide" placeholder="3.5" value="{{ relance.type_relance.relance_call_duration }}">
                    <span class="form-error call_durantion-error"></span>
                </div>

                <div class="form-group">
                    <label for="relance_feedback">Feedback patient</label>
                    <select name="relance_feedback" id="relance_feedback" class="form-control">
                        <option value="">Sélectionner le feedback</option>
                        {% for feed in feedback %}
                        <option {% if relance.feedback.type == feed %}selected{% endif %} value="{{feed|lower}}">{{feed|upper}}</option>
                        {% endfor %}
                    </select>
                    <span class="form-error relance_feedback-error"></span>
                </div>

                <div class="form-group hide" data-feedback-visite-date>
                    <label for="feedback_visite_date">Date de visite</label>
                    <input type="date" name="feedback_visite_date" id="feedback_visite_date" class="form-control hide" value="{{relance.feedback.visite_date}}">
                    <span class="form-error feedback_visite_date-error"></span>
                </div>

                <div class="form-group hide" data-feedback-other-center>
                    <label for="feedback_other_center">Date de visite</label>
                    <input type="text" name="feedback_other_center" id="feedback_other_center" class="form-control hide" value="{{relance.feedback.new_center}}">
                    <span class="form-error feedback_visite_date-error"></span>
                </div>

                <div class="form-group hide" data-feedback-description>
                    <label for="feedback_description">Feedback description</label>
                    <textarea name="feedback_description" id="feedback_description" placeholder="Message" class="form-control hide">{{relance.feedback.description}}</textarea>
                    <span class="form-error feedback_description-error"></span>
                </div>

                <div class="form-group">
                    <label for="relance_comment">Commentaire</label>
                    <textarea name="relance_comment" id="relance_comment" placeholder="Commentaire" class="form-control">{{relance.comment}}</textarea>
                    <span class="form-error relance_comment-error"></span>
                </div>

                <button type="submit" class="button button-gradient"><i class="flaticon-floppy-disk"></i> Enregistrer</button>

            </form>
        </div>

        </div>
    </section>

{% endblock content %}

relance_patient/templates/relance_patient/index.html
{% extends 'master.html' %}

{% block title %}Relance patient{% endblock title %}

{% block content %}
    
    <section class="home-section user-section">

        <div class='section-block'>
            <a href="{% url 'activite_relance:add_relance' %}" class="button button-gradient add-user"><i class="flaticon-plus-1"></i> Ajouter une relance</a>
        </div>
        <div class="card">
            <table class="table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Code patient</th>
                        {% comment %} <th>Numéro patient</th> {% endcomment %}
                        <th>Motif</th>
                        <th>Type de relance</th>
                        <th>Durée appel</th>
                        <th>Feedback</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% if relances|length == 0 %}
                        <tr>
                            <td style="text-align:center">
                                Aucune relance n'est enregistrée
                            </td>
                        </tr>
                    {% else %}
                    {% for relance in relances %}
                    <tr>   

                        <td>{{ relance.relance_date| date }}</td>

                        <td>{{ relance.patient_code | upper }}</td>

                        {% comment %} <td>{{ relance.patient_contact }}</td> {% endcomment %}

                        <td>{{ relance.relance_reason | upper }}</td>

                        <td>{{ relance.type_relance.type | upper }}</td>

                        {% if relance.type_relance.relance_call_duration %}
                            <td>{{ relance.type_relance.relance_call_duration }} MIN</td>
                        {% else %}
                            <td>-</td>
                        {% endif %}

                       

                        <td>{{ relance.feedback.type | upper }}</td>

                

                        <td class="action">

                            <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="relance_code" value="{{ relance.relance_code }}">
                                {% comment %} <a data-archive-relance href="{% url 'activite_relance:archive_relance' relance_code=relance.relance_code %}" class="button button-small button-ouline-dark"><i class="flaticon-file-1"></i></a> {% endcomment %}
                                <a data-edit-relance href="{% url 'activite_relance:edit_relance' relance_code=relance.relance_code %}" class="button button-small button-ouline-success"><i class="flaticon-edit"></i></a>
                                {% comment %} <a data-delete-relance href="" class="button button-small button-ouline-danger"><i class="flaticon-trash"></i></a> {% endcomment %}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}

                    {% endif %}
                </tbody>
            </table>
        </div>
    </section>

{% endblock content %}